### ISSUE TITLE
Results on TruffleRuby

### ISSUE THREAD

**Issue by eregon** [fujimotos/RubyKaigi2022#1]
Hello,
I was reading your slides and I was curious how fast TruffleRuby is on the LTSV benchmark.
I've run it locally and here are the results: https://twitter.com/eregontp/status/1569272450051108869, i.e.,
TruffleRuby is 3.6x (CE) and 5.7x (EE) faster than CRuby 3.1 on that benchmark!

I would @-mention you on Twitter instead but I couldn't find your Twitter profile (if you have one), so I open this issue instead to let you know (feel free to close this issue of course).

**Comment by fujimotos** [comment]
> TruffleRuby is 3.6x (CE) and 5.7x (EE) faster than CRuby 3.1 on that benchmark!

@eregon Nice! I took a look at your numbers in the tweet. It's really promissing!

So I started watching your [RubyKaigi2021 presentation](https://rubykaigi.org/2021-takeout/presentations/eregontp.html) to learn TruffleRuby.
(btw, I don't think I saw your talk anywhere in RubyKaigi2022's talk list -- 
which IMO you _really_ should have given one; Ruby definitely needs more
performance talks).

And now, TruffleRuby is already working on my machine:

```console
fujimoto:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

fujimoto:~$ ruby -v
truffleruby 22.2.0, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]
```

I'll find some time tinkering with TruffleRuby + Fluentd. Thank you for
letting me know about your great work!

**Comment by eregon** [comment]
> (btw, I don't think I saw your talk anywhere in RubyKaigi2022's talk list -- which IMO you really should have given one; Ruby definitely needs more performance talks).

I wasn't able to travel this year and it was also not recommended to come from abroad at the time of the CFP.
Hopefully I can make it for the next RubyKaigi :)

I'm quite interested to see how Truffleruby performs on typical fluentd workloads, I have seen a few people asking how fluentd performs on TruffleRuby.
I have also created https://github.com/fluent/fluentd/discussions/3893 as I am not sure what would be a good fluentd benchmark.

**Comment by fujimotos** [comment]
> I have also created https://github.com/fluent/fluentd/discussions/3893 as I am not sure what would be a good fluentd benchmark.

I just posted some comment there. Hope it helps.

> Hopefully I can make it for the next RubyKaigi :)

Nice! I'm looking forward to listening to your talk next time.
